version: "3.8"

services:
  mongo:
    image: mongo:6.0
    container_name: mongo-lab
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: labdb
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db
      - ./init:/docker-entrypoint-initdb.d
    command: ["--replSet", "rs0", "--bind_ip_all"]
